name: Build Test

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  # Test and Build Backend (NestJS)
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./order-team-be

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './order-team-be/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build application
        run: npm run build

  # Test and Build Frontend (Next.js)
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./order-team-fe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './order-team-fe/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Build application
        run: npm run build
